// <auto-generated />
using System;
using ELMSAPI.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELMSAPI.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241029100733_Added_Users_Table")]
    partial class Added_Users_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ELMSAPI.Domain.Models.LeaveStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeaveStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(5893),
                            DateModified = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(5906),
                            Description = "Pending",
                            Status = "I"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(5907),
                            DateModified = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(5908),
                            Description = "Approved",
                            Status = "I"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(5909),
                            DateModified = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(5910),
                            Description = "Rejected",
                            Status = "I"
                        });
                });

            modelBuilder.Entity("ELMSAPI.Domain.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(6009),
                            DateModified = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(6010),
                            Status = "I",
                            Type = "Annual"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(6012),
                            DateModified = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(6012),
                            Status = "I",
                            Type = "Sick"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(6014),
                            DateModified = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(6014),
                            Status = "I",
                            Type = "Maternity"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(6015),
                            DateModified = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(6016),
                            Status = "I",
                            Type = "Paternity"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(6017),
                            DateModified = new DateTime(2024, 10, 29, 14, 7, 32, 556, DateTimeKind.Local).AddTicks(6018),
                            Status = "I",
                            Type = "Unpaid"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
